version: '3.7'

services:
  app:
    container_name: go_validator_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # Load environment variables from .env file
    ports:
      - "9090:8080" # Map port 8080 in the container to port 9090 on the host